# Generated by Django 5.2.3 on 2025-07-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
